import { DayDelimiterData, HourDelimiterData, StatisticData, WeekDelimiterData } from './core/delimiter-data';

export const daysMock: HourDelimiterData[] = <StatisticData[]>[
  // {
  //   views: 1,
  //   cost: 1,
  //   day: '9',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 0,
  //   cost: 0,
  //   day: '10',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 0,
  //   cost: 0,
  //   day: '11',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 0,
  //   cost: 0,
  //   day: '12',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 0,
  //   cost: 0,
  //   day: '13',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 0,
  //   cost: 0,
  //   day: '14',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },

  // {
  //   views: 571,
  //   cost: 191.7778,
  //   day: '15',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 587,
  //   cost: 204.7657,
  //   day: '16',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 566,
  //   cost: 200.1885,
  //   day: '17',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 599,
  //   cost: 203.0128,
  //   day: '18',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 567,
  //   cost: 197.1810,
  //   day: '19',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 561,
  //   cost: 202.5299,
  //   day: '20',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 643,
  //   cost: 231.9028,
  //   day: '21',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 599,
  //   cost: 203.0128,
  //   day: '22',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 567,
  //   cost: 97.1810,
  //   day: '23',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  // {
  //   views: 561,
  //   cost: 10.5299,
  //   day: '24',
  //   month: '3',
  //   year: '2019',
  //   hour: null,
  //   week: null,
  // },
  {
    views: 643,
    cost: 231.9028,
    day: '14',
    month: '7',
    year: '2019',
    hour: null,
    week: null,
  },
];
export const hoursMock: DayDelimiterData[] = <StatisticData[]>[
  {
    views: 40,
    cost: 130.0298,
    day: '17',
    month: '7',
    year: '2019',
    hour: '2',
    week: null,
  },
  {
    views: 500,
    cost: 12.1090,
    day: '17',
    month: '7',
    year: '2019',
    hour: '4',
    week: null,
  },
  {
    views: 423,
    cost: 130.0298,
    day: '17',
    month: '7',
    year: '2019',
    hour: '5',
    week: null,
  },
];
export const weeksMock: WeekDelimiterData[] = <StatisticData[]>[
  {
    views: 1158,
    cost: 396.5435,
    day: null,
    month: '3',
    year: '2019',
    hour: null,
    week: '10',
  },
  {
    views: 4119,
    cost: 1448.9926,
    day: null,
    month: '3',
    year: '2019',
    hour: null,
    week: '11',
  },
  {
    views: 2897,
    cost: 1011.4518,
    day: null,
    month: '3',
    year: '2019',
    hour: null,
    week: '12',
  },
  {
    views: 1,
    cost: 0.2018,
    day: null,
    month: '3',
    year: '2019',
    hour: null,
    week: '13',
  },
  {
    views: 2266,
    cost: 799.0618,
    day: null,
    month: '4',
    year: '2019',
    hour: null,
    week: '14',
  },
  {
    views: 584,
    cost: 216.0682,
    day: null,
    month: '4',
    year: '2019',
    hour: null,
    week: '15',
  },
];
